spring:
  application:
    name: SecurityMs-Dev
  config:
    import: consul://casalocal.com:8500/config/SecurityMs-Dev
  cloud:
    consul:
      config:
        enabled: true
        format: YAML
      discovery:
        enabled: true
