spring:
  application:
    name: UserMs-Dev
  config:
    import: consul://casalocal.com:8500/config/UserMs-Dev
  cloud:
    consul:
      config:
        enabled: true
        format: YAML
      discovery:
        enabled: true
        health-check-interval: 60s # Set the interval to 30 seconds
        health-check-path: /actuator/health # Health check endpoint
        health-check-timeout: 3s # Timeout for the health check
